from handlers.user_private import user_private_router
from handlers.user_private_checked import user_private_checked

routers = [user_private_router]
user_private_router.include_router(user_private_checked)